spring:
  profiles:
    active:
      - local
    group:
      local:
        - local
        - local-db
        - secret
      prod:
        - prod
        - prod-db
        - secret
#    include:
#      - secret