spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(uEIVoILKaVA624A5eU2Rszwz8oWe5M8Qg4gkbZPZKdMbwGFb4NqacVlshdtd0mwK)
            client-secret: ENC(UTZMJf32yZVF/GpjGOiFIWz7ZHNHpzOuwmorl6rrS/kAVK4S2VYUjRhML0G7OUCu)
            redirect-uri: ENC(fehA5qKoU4jzaSIEYL3gZvWXlGxMPbBqs3VsSa5QcvDo2GZPQwgjgJHQW5MaHxJEyUylu0MVZ18=)
            authorization-grant-type: authorization_code
            scope: profile_nickname,profile_image,account_email

          naver:
            client-id: ENC(TfKo7PyEwmlqfd78g0Wv1fIgzVRG3F6iC83Fuzobc88=)
            client-secret: ENC(g0oD7nVVUnXX88YOZllrz5HVnqQyMO9q)
            redirect-uri: ENC(7BvhzYKlLYDqb5P+ib9a7Tk0FKT6NC3gVDl8TJunmuwmZ1NLEJP3VvfaK2akE0GmR5DwGWXju5pvxj1EmluyJfYwRfPbFlWd)
            authorization-grant-type: authorization_code
            state: ENC(RrVftPSK0JRPMs3oUx+kXADjylrpffpD)

          google:
            client-id: ENC(JIB2Zi/ozlrvkvunz7RqZvDCNWXTBws+8ppVqZJTY+/zcCxtIIeHO0p99O5Zre91NPYVxtdNFk+RWQ3TRDmf1Fhi3EBv3ZEXcyG8Q0YDrWn53vfiK5x1ig==)
            client-secret: ENC(8uVuXtVW/ftqR2uEzsxCLRfj7v7rRdwlLgkuj/RoH02zYMYTl0786g46bkP0TQVH)
            redirect-uri: ENC(2LG+p6QOksDxQzLoL/WW5Ajh1W1mT7ImZEy78Szke26JQS+EKyNFsIZ2zD8xJw2aIhWnYbugwqg=)
            authorization-grant-type: authorization_code
            scope: email,profile

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            issuer-uri: https://kauth.kakao.com
            user-info-uri: https://kapi.kakao.com/v2/user/me
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-name-attribute: sub

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v1/userinfo
            user-name-attribute: sub

application:
  security:
    jwt:
      secret-key: ENC(02jYhnuuQa+qzHVir/lJdIHjgkIglLrF0qqKg+WhNJUU2KYQaB1nt9at+2Wg9bQhO4DG76P/VQJiSHp9LtNdQviTc+4fnW3ZeE9DXBSs2FY=)
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

jasypt:
  encryptor:
    bean: jasyptStringEncryptor